import Head from "next/head";
import CurveTransition from "@/components/transition/CurveTransition";

import { Inter } from "next/font/google";

import { useEffect } from "react";
import Contact from "@/components/ContactPage/Contact";
import Calendly from "@/components/ContactPage/Calendly";
import dynamic from "next/dynamic";

import Navbar from "@/components/common/Navbar";
import Header from "@/components/common/Header";
const Footer = dynamic(() => import('@/components/ContactPage/Footer'), { ssr: false });


const inter = Inter({ subsets: ["latin"] });

export default function Home() {

  useEffect(() => {
    if (typeof window !== 'undefined') {
      import('locomotive-scroll').then(LocomotiveScroll => {
        const scroll = new LocomotiveScroll.default({
          el: document.querySelector('[data-scroll-container]'),
          smooth: true,
        });

        return () => {
          if(scroll) scroll.destroy();
        };
      });
    }
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Navbar />
      <CurveTransition>
        <Contact />
        <Calendly />
         <Footer />
      </CurveTransition>
    </>
  );
}
