import Head from "next/head";
import CurveTransition from "@/components/transition/CurveTransition";

import Calendly from "@/components/ContactPage/Calendly";
import dynamic from "next/dynamic";

import Navbar from "@/components/common/Navbar";
import Header from "@/components/common/Header";
import { usePathname } from "next/navigation";
import { useEffect, useState } from "react";
const Footer = dynamic(() => import('@/components/ContactPage/Footer'), { ssr: false });
const Contact = dynamic(() => import('@/components/ContactPage/Contact'), { ssr: false });

export default function Home() {
  const pathname = usePathname()

  const [isLoading, setIsLoading] = useState(true);
  // to always return to the top of the page when the page changes
  // its easier to look for changes in the pathname then to look for changes in the router object

  useEffect(() => {
    setTimeout(() => {
      window.scrollTo(0, 0);
    }, 1500);
  }, [pathname]);

  useEffect( () => {
    (
      async () => {
          const LocomotiveScroll = (await import('locomotive-scroll')).default
          const locomotiveScroll = new LocomotiveScroll();

          setTimeout( () => {
            setIsLoading(false);
            document.body.style.cursor = 'default'
            if (typeof window !== 'undefined') {
              window.scrollTo(0,0);
            }
          }, 2000)
      }
    )()
  }, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Navbar />
      <CurveTransition>
        <Contact />
        <Calendly />
         <Footer />
      </CurveTransition>
    </>
  );
}
