import Head from "next/head";
import CurveTransition from "@/components/transition/CurveTransition";
import dynamic from 'next/dynamic';
const Projects = dynamic(() => import('@/components/ProjectsPage/Projects'), { ssr: false });

import Footer from "@/components/common/Footer";
import Navbar from "@/components/common/Navbar";
import Header from "@/components/common/Header";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Navbar />
      <CurveTransition>
        <Projects />
        <Footer />
      </CurveTransition>
    </>
  );
}
