import Head from "next/head";
import CurveTransition from "@/components/transition/CurveTransition";
import IntroText from "@/components/common/IntroText"
import FreeOffers from "@/components/common/FreeStuff";

import Footer from "@/components/common/Footer";
import Navbar from "@/components/common/Navbar";
import Header from "@/components/common/Header";
import Landing from "@/components/MaterialsPage/Landing";
import { useEffect, useState } from "react";

//LOREM IPSUM DOLOR SIT AMET, CONSECTETUR ADIPISCING ELIT. PROIN IN ERAT LIGULA. VESTIBULUM ELEMENTUM EX ET TELLUS MALESUADA, QUIS CONSECTETUR ORCI CONSECTETUR. VESTIBULUM VOLUTPAT, EST SOLICITUDIN POSUERE CONGUE, AUGUE AUGUE DAPIBUS ENIM, A MAXIMUS NUNC EX EGET DUI. PRAESENT ID VENENATIS QUAM, A EFFICITUR LEO. QUISQUE MAURIS MAGNA, MOLLIS A PHARETRA SED, PLACERAT AUCTOR NISI. ETIAM BIBENDUM NEQUE SIT AMET MI TEMPUS, ID ULLAMCORPER URNA ULTRICIES. PELLENTESQUE VOLUTPAT MASSA AT TORTOR MATTIS, ID SAGITTIS EST FEUGIAT.
//Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin in erat ligula. Vestibulum elementum ex et tellus malesuada, quis consectetur orci consectetur. Vestibulum volutpat, est sollicitudin posuere congue, augue augue dapibus enim, a maximus nunc ex eget dui. Praesent id venenatis quam, a efficitur leo. Quisque mauris magna, mollis a pharetra sed, placerat auctor nisi. Etiam bibendum neque sit amet mi tempus, id ullamcorper urna ultricies. Pellentesque volutpat massa at tortor mattis, id sagittis est feugiat.

const phrases = [
  {
      text: "Za své 2 roky zkušeností a téměř <span>3000 hodin</span> jsem dal dohormady ekostystém složený z <span>principů</span>,které zahrnují <span>dobrý design</span>,<span>uživatelský zážitek</span> a <span>neodolatelnou obchodní nabídku</span>."
  },
  {
      text: "Jsem si moc dobře vědom kolik <span>času, píle, chyb a drahých omylů</span> stojí mít výkonný a effektivní ekosystém ve všech těchto aspektů.<span>Plánuji proto,</span> pro všechny, kteří začínají, dát tyhle zkušenosti <span>ven mezi Vás.</span> S cenou vašeho času."
  },
  {
      text: "Jediný od Vás chci,<span> je vaše důvěra a čas, který budete věnovat</span> sledováním a čtěním mých budoucích materiálů.<span>Dejte mi tak ještě čas,</span>abych Vám mohl přinést <span>to nejjednodušší a nejefektivnější zároveň.</span> Pěkně těžká kombinace,<span>ale vím že to nebude za dlouho.</span>"
  }
]

export default function Home() {
  const [isActive, setIsActive] = useState(false);
  const [isLoading, setIsLoading] = useState(true);

  useEffect( () => {
    (
      async () => {
          const LocomotiveScroll = (await import('locomotive-scroll')).default
          const locomotiveScroll = new LocomotiveScroll();

          setTimeout( () => {
            setIsLoading(false);
            document.body.style.cursor = 'default'
            if (typeof window !== 'undefined') {
              window.scrollTo(0,0);
            }
          }, 2000)
      }
    )()
  }, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header isActive={isActive} setIsActive={setIsActive}/>
      <Navbar isActive={isActive} setIsActive={setIsActive}/>
      <CurveTransition>
        <div className="page">
          <Landing />
          <IntroText phrases={phrases} />
          <FreeOffers />
          <Footer />
        </div>
        
      </CurveTransition>
    </>
  );
}
